apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - powerbi-configmap.yaml
  - worker-cronjob.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml
images:
  - name: neople-game-analytics-worker
    newName: registry.gitlab.com/replace_with_group/neople-game-analytics/worker
    newTag: latest
  - name: neople-game-analytics-api
    newName: registry.gitlab.com/replace_with_group/neople-game-analytics/api
    newTag: latest
  - name: neople-game-analytics-web
    newName: registry.gitlab.com/replace_with_group/neople-game-analytics/web
    newTag: latest
