FROM nginx:1.27-alpine

COPY web/index.html /usr/share/nginx/html/index.html
COPY web/app.js /usr/share/nginx/html/app.js
COPY web/styles.css /usr/share/nginx/html/styles.css
COPY web/data /usr/share/nginx/html/data
COPY deploy/nginx/web.conf /etc/nginx/templates/default.conf.template

EXPOSE 8080
